### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Faragopetergy** [r-a-y/unlisted-posts#4]
Hi Ray!
I really would like to know that how I could install this plugin, because I cannot find in the plugin store of Wordpress. Much thanks for your reply in advance! :)

**Comment by r-a-y** [comment]
Hi,

Thanks for the interest.  Currently, the plugin is only available on Github.

To install, download the ZIP package:
https://github.com/r-a-y/unlisted-posts/archive/master.zip

And extract to your `wp-content/plugins` folder.  Then, activate as usual.

**Comment by Faragopetergy** [comment]
It's very great. Much thanks for your help and for your plugin. :)
